version: 0.2

phases:
  build:
    commands:
      - pip install --upgrade awscli
      - aws cloudformation deploy --template-file template.yml --stack-name $STACK_NAME
      - npm install
      - ng run ngbuild
      - UI_BUCKET=“$(aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query 'Stacks[0].Outputs[?OutputKey==`PapersubmissionBucket`].[OutputValue]' --output text)"
      - aws s3 sync dist "${UI_BUCKET}" --acl public-read --delete
artifacts:
  type: zip
  files:
    - template-export.yml
