version: 0.2

phases:
  build:
    commands:
      - pip install --upgrade awscli
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - aws cloudformation deploy --template-file template-export.yml --stack-name $STACK_NAME --capabilities "CAPABILITY_NAMED_IAM"
      - npm install
      - ng run ngbuild
      - UI_BUCKET=“$(aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query ‘Stacks[?StackName==`${STACK_NAME}`].Outputs[*].{key:OutputKey, value:OutputValue}’ --output text)”
      - aws s3 sync dist "${UI_BUCKET}" --acl public-read --delete

artifacts:
  type: zip
  files:
    - template-export.yml
