version: 0.2

phases:
  build:
    commands:
      - pip install --upgrade awscli
      - npm install
      - npm install -g @angular/cli
      - npm run ngbuild
      - UI_BUCKET=“$(aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query 'Stacks[0].Outputs[?OutputKey==`PapersubmissionBucket`].[OutputValue]' --output text)"
      - echo $UI_BUCKET
      - aws s3 sync dist "${UI_BUCKET}" --acl public-read --delete
artifacts:
  type: zip
  files:
    - template-export.yml
