AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3Bucket:
    Type: String
    MaxLength: 64
    Description: an Name to create distinct ressources for every member

Resources:
  PapersubmissionUIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'S3Bucket'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Delete

Outputs:
  PapersubmissionBucket:
    Description: UI S3 Bucket
    Value: !Ref PapersubmissionUIBucket
