AWSTemplateFormatVersion: 2010-09-09

Resources:
  PapersubmissionUIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['.', [!Ref 'AWS::StackName', !Ref 'AWS::AccountId', 'angular-ui', 'oc-papersubmission']]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Delete

Outputs:
  PapersubmissionBucket:
    Description: UI S3 Bucket
    Value: !Ref PapersubmissionUIBucket
