AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3Prefix:
    Default: 'angular'
    Type: String
    MaxLength: 10
    Description: an Name to create distinct ressources for every member

Resources:
  PapersubmissionUIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref 'S3Prefix', !Ref 'AWS::AccountId', 'oc-papersubmission', 'ui']]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Delete

Outputs:
  PapersubmissionBucket:
    Description: UI S3 Bucket
    Value: !Ref PapersubmissionUIBucket
